//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGamesStore.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistGame
    {
        public int id { get; set; }
        public int Artist { get; set; }
        public int Game { get; set; }
    
        public virtual Artists Artists { get; set; }
        public virtual Games Games { get; set; }
    }
}
