//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGamesStore.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenreGame
    {
        public int Id { get; set; }
        public int Genre { get; set; }
        public int Game { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
