//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGamesStore.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BGSEntities : DbContext
    {
        public BGSEntities()
            : base("name=BGSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArtistGame> ArtistGame { get; set; }
        public virtual DbSet<Artists> Artists { get; set; }
        public virtual DbSet<Designer> Designer { get; set; }
        public virtual DbSet<DesignerGame> DesignerGame { get; set; }
        public virtual DbSet<Games> Games { get; set; }
        public virtual DbSet<GenreGame> GenreGame { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<PublisherGame> PublisherGame { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
