//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGamesStore.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BGSEntities : DbContext
    {
        public BGSEntities()
            : base("name=BGSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArtistGame> ArtistGame { get; set; }
        public virtual DbSet<Artists> Artists { get; set; }
        public virtual DbSet<DesignerGame> DesignerGame { get; set; }
        public virtual DbSet<Games> Games { get; set; }
        public virtual DbSet<GenreGame> GenreGame { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<PublisherGame> PublisherGame { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Designers> Designers { get; set; }
    }
}
